<?php

namespace Rumbo\AppBundle\Entity;

/**
 * AgenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByNombre()
    {
        return $this->createQueryBuilder('a')
            ->addOrderBy('a.nombre')
            ->getQuery()
            ->getResult();

    }
}
