<?php

namespace Rumbo\AppBundle\Entity;

/**
 * CiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiaRepository extends \Doctrine\ORM\EntityRepository
{
}
