<?php

namespace Rumbo\AppBundle\Entity;

/**
 * FaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaseRepository extends \Doctrine\ORM\EntityRepository
{
}
