<?php

namespace Rumbo\AppBundle\Entity;

/**
 * ProfesionalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionalesRepository extends \Doctrine\ORM\EntityRepository
{
}
