<?php

namespace Rumbo\AppBundle\Entity;

/**
 * SiniestroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiniestroRepository extends \Doctrine\ORM\EntityRepository
{
}
