<?php

namespace Rumbo\AppBundle\Entity;

/**
 * tramitadorCiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tramitadorCiaRepository extends \Doctrine\ORM\EntityRepository
{
}
